### ISSUE TITLE
SciPy builds are failing with gast 0.5.4

### ISSUE THREAD

**Issue by tylerjereddy** [serge-sans-paille/gast#74] opened 2023-04-30 22:27 UTC
SciPy `meson` source builds work with `gast 0.5.3` but not `0.5.4` per https://github.com/scipy/scipy/issues/18390#issuecomment-1529153916.

**Comment by Tatsh** [comment] 2023-05-01 08:09
https://github.com/serge-sans-paille/pythran/issues/2101#issuecomment-1529462985

**Comment by Tatsh** [comment] 2023-05-01 08:12
Caused by this https://github.com/serge-sans-paille/gast/compare/0.5.3...0.5.4#diff-44b67094998a7df1e5ce843b5a2faa44950f5896ac9e07ab99d09e2b24c90143R13

**Comment by serge-sans-paille** [comment] 2023-05-01 20:45
And fixed by https://github.com/serge-sans-paille/pythran/issues/2100

**Comment by h-vetinari** [comment] 2023-05-02 07:18
> And fixed by [serge-sans-paille/pythran#2100](https://github.com/serge-sans-paille/pythran/pull/2100)

Since that causes yet another breakage, could we take a step back and find a less stressful way to roll out this upgrade?

Alternatives I can think of:
* Backport https://github.com/serge-sans-paille/pythran/commit/f0c2777d41a71ce78969707487161b1d4555e599 to pythran 0.12 and release 0.12.2
* Yank gast 0.5.4

Context: The CI of scipy (and other projects) has been broken for ~2 days now. This is not a good place to be and while I appreciate that regressions can happen, I'd hope that this situation could get unbroken first before we wait for the next fixes on top.

**Closed** 2024-03-09 06:58 UTC
